//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dmitriev_5.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.OrderItems = new HashSet<OrderItems>();
        }
    
        public int EquipmentID { get; set; }
        public string Model { get; set; }
        public string Manufacturer { get; set; }
        public int CategoryID { get; set; }
        public int SupplierID { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Dimensions { get; set; }
        public Nullable<int> PowerConsumption { get; set; }
        public Nullable<int> MaxPrintSpeed { get; set; }
        public string MaxPrintFormat { get; set; }
        public string Technology { get; set; }
        public Nullable<bool> IsInStock { get; set; }
        public Nullable<int> WarrantyMonths { get; set; }
    
        public virtual EquipmentCategories EquipmentCategories { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual ICollection<OrderItems> OrderItems { get; set; }
    }
}
